from fastapi import APIRouter
from app.api.v1 import scans, clients, competitors, control_queries, toolkit, site_audit, activity, digest, reports, content_gaps, content_roadmap, action_center, traffic, client_view, costs, remediation, citability, deliverables, authority, work_log, work_log_global, misinformation, outcome_actions, action_approvals, locations, truth_vault, tracked_queries, search_console, conversion_events, business_impact, query_stability, benchmarks, benchmark_publications, public_benchmarks, market_intelligence

router = APIRouter(prefix="/api/v1")
router.include_router(scans.router)
router.include_router(clients.router)
router.include_router(competitors.router)
router.include_router(control_queries.router)
router.include_router(toolkit.router)
router.include_router(site_audit.router)
router.include_router(activity.router)
router.include_router(digest.router)
router.include_router(reports.router)
router.include_router(content_gaps.router)
router.include_router(content_roadmap.router)
router.include_router(action_center.router)
router.include_router(traffic.router)
router.include_router(client_view.router)
router.include_router(costs.router)
router.include_router(remediation.router)
router.include_router(citability.router)
router.include_router(deliverables.router)
router.include_router(authority.router)
router.include_router(work_log.router)
router.include_router(work_log_global.router)
router.include_router(misinformation.router)
router.include_router(outcome_actions.router)
router.include_router(action_approvals.router)
router.include_router(locations.router)
router.include_router(truth_vault.router)
router.include_router(tracked_queries.router)
router.include_router(search_console.router)
router.include_router(conversion_events.router)
router.include_router(business_impact.router)
router.include_router(query_stability.router)
router.include_router(benchmarks.router)
router.include_router(benchmark_publications.router)
router.include_router(public_benchmarks.router)
router.include_router(market_intelligence.router)
