# backend/app/services/toolkit_service.py
import json
from concurrent.futures import ThreadPoolExecutor

from app.models.client import Client
from app.services.claude_client import MODEL as _MODEL
from app.services.claude_client import anthropic_client as _anthropic_client
from app.services.claude_client import strip_code_fences as _strip_code_fences


def generate_llms_txt(client: Client) -> str:
    response = _anthropic_client().messages.create(
        model=_MODEL,
        max_tokens=2048,
        messages=[
            {
                "role": "user",
                "content": f"""Generate an llms.txt file for this business.
llms.txt is a standard file (similar to robots.txt) that helps AI language models understand a website.
Follow the Answer.AI spec: start with # Brand Name on the first line, then > short one-sentence tagline, then markdown sections with relevant information.

Business details:
Name: {client.name}
Website: {client.website}
Industry: {client.industry}
Description: {client.description or 'Not provided'}
Target audience: {client.target_audience or 'Not provided'}
City: {client.city or 'Not provided'}
State: {client.state or 'Not provided'}

Output ONLY the raw llms.txt content. No explanations. No code block wrappers.""",
            }
        ],
    )
    return response.content[0].text.strip()


def generate_schema_json(client: Client) -> str:
    prompt = f"""Generate a JSON-LD structured data file for this business.
Include these schema types in a @graph array:
1. LocalBusiness (or an appropriate subtype like ProfessionalService, Restaurant, etc.)
2. Organization
3. FAQPage with 3-5 realistic FAQ items about this specific business

Business details:
Name: {client.name}
Website: {client.website}
Industry: {client.industry}
Description: {client.description or 'Not provided'}
City: {client.city or 'Not provided'}
State: {client.state or 'Not provided'}

Output ONLY valid JSON. No explanations. No ```json code block wrapper. Start directly with the opening brace."""

    for attempt in range(2):
        response = _anthropic_client().messages.create(
            model=_MODEL,
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = _strip_code_fences(response.content[0].text)
        try:
            json.loads(raw)
            return raw
        except json.JSONDecodeError:
            if attempt == 1:
                raise ValueError(
                    f"Claude returned invalid JSON after 2 attempts for client {client.id}"
                )

    raise ValueError("Should not reach here")  # pragma: no cover


def generate_robots_txt(client: Client) -> str:
    return f"""# AI Search Bot Access — generated by SeenBy
# Add these lines to your existing robots.txt file at {client.website}/robots.txt
# If you don't have a robots.txt yet, this file is ready to use as-is.

User-agent: *
Allow: /

User-agent: GPTBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /"""


def generate_toolkit_files(client: Client) -> dict[str, str]:
    with ThreadPoolExecutor(max_workers=2) as executor:
        llms_future = executor.submit(generate_llms_txt, client)
        schema_future = executor.submit(generate_schema_json, client)
        robots = generate_robots_txt(client)
        return {
            "llms_txt": llms_future.result(),
            "schema_json": schema_future.result(),
            "robots_txt": robots,
        }
