# backend/app/services/toolkit_service.py
import anthropic
from app.core.config import settings
from app.models.client import Client

_MODEL = "claude-haiku-4-5-20251001"


def _anthropic_client() -> anthropic.Anthropic:
    return anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)


def generate_llms_txt(client: Client) -> str:
    response = _anthropic_client().messages.create(
        model=_MODEL,
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""Generate an llms.txt file for this business.
llms.txt is a standard file (similar to robots.txt) that helps AI language models understand a website.
Follow the Answer.AI spec: start with # Brand Name on the first line, then > short one-sentence tagline, then markdown sections with relevant information.

Business details:
Name: {client.name}
Website: {client.website}
Industry: {client.industry}
Description: {client.description or 'Not provided'}
Target audience: {client.target_audience or 'Not provided'}
City: {client.city or 'Not provided'}
State: {client.state or 'Not provided'}

Output ONLY the raw llms.txt content. No explanations. No code block wrappers.""",
            }
        ],
    )
    return response.content[0].text.strip()


def generate_schema_json(client: Client) -> str:
    response = _anthropic_client().messages.create(
        model=_MODEL,
        max_tokens=2048,
        messages=[
            {
                "role": "user",
                "content": f"""Generate a JSON-LD structured data file for this business.
Include these schema types in a @graph array:
1. LocalBusiness (or an appropriate subtype like ProfessionalService, Restaurant, etc.)
2. Organization
3. FAQPage with 3-5 realistic FAQ items about this specific business

Business details:
Name: {client.name}
Website: {client.website}
Industry: {client.industry}
Description: {client.description or 'Not provided'}
City: {client.city or 'Not provided'}
State: {client.state or 'Not provided'}

Output ONLY valid JSON. No explanations. No ```json code block wrapper. Start directly with the opening brace.""",
            }
        ],
    )
    return response.content[0].text.strip()


def generate_robots_txt(client: Client) -> str:
    return f"""# AI Search Bot Access — generated by SeenBy
# Add these lines to your existing robots.txt file at {client.website}/robots.txt

User-agent: GPTBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /"""


def generate_toolkit_files(client: Client) -> dict[str, str]:
    return {
        "llms_txt": generate_llms_txt(client),
        "schema_json": generate_schema_json(client),
        "robots_txt": generate_robots_txt(client),
    }
