# backend/app/services/toolkit_service.py
import json
from concurrent.futures import ThreadPoolExecutor

from app.models.client import Client
from app.prompts.toolkit import build_llms_txt, build_schema_json
from app.services.claude_client import MODEL as _MODEL
from app.services.claude_client import anthropic_client as _anthropic_client
from app.services.claude_client import strip_code_fences as _strip_code_fences
from app.services.cost_tracker import record_llm_call


def generate_llms_txt(client: Client) -> str:
    response = _anthropic_client().messages.create(
        model=_MODEL,
        max_tokens=2048,
        messages=[{"role": "user", "content": build_llms_txt(client)}],
    )
    record_llm_call(service="toolkit_llms_txt", model=_MODEL, response=response, client_id=client.id)
    # Haiku occasionally wraps output in a ``` fence despite the instruction above;
    # strip it so a stray fence never lands in the published llms.txt file.
    return _strip_code_fences(response.content[0].text)


def generate_schema_json(client: Client) -> str:
    prompt = build_schema_json(client)
    for attempt in range(2):
        response = _anthropic_client().messages.create(
            model=_MODEL,
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        record_llm_call(
            service="toolkit_schema_json", model=_MODEL, response=response, client_id=client.id
        )
        raw = _strip_code_fences(response.content[0].text)
        try:
            json.loads(raw)
            return raw
        except json.JSONDecodeError:
            if attempt == 1:
                raise ValueError(
                    f"Claude returned invalid JSON after 2 attempts for client {client.id}"
                )

    raise ValueError("Should not reach here")  # pragma: no cover


def generate_robots_txt(client: Client) -> str:
    return f"""# AI Search Bot Access — generated by SeenBy
# Add these lines to your existing robots.txt file at {client.website}/robots.txt
# If you don't have a robots.txt yet, this file is ready to use as-is.

User-agent: *
Allow: /

User-agent: GPTBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Google-Extended
Allow: /"""


def generate_toolkit_files(client: Client) -> dict[str, str]:
    with ThreadPoolExecutor(max_workers=2) as executor:
        llms_future = executor.submit(generate_llms_txt, client)
        schema_future = executor.submit(generate_schema_json, client)
        robots = generate_robots_txt(client)
        return {
            "llms_txt": llms_future.result(),
            "schema_json": schema_future.result(),
            "robots_txt": robots,
        }
